// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
// Runtime validation is required; types do not encode all schema constraints.

pub type NonEmptyString = String;

pub type Identifier = String;

pub type Counter = crate::SafeInteger;

pub type PositiveCounter = crate::SafeInteger;

pub type Sha256 = String;

pub type SnapshotHash = String;

pub type ContentRef = String;

pub type UtcTimestamp = String;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Effect {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "local_write")]
    LocalWrite,
    #[serde(rename = "external_write")]
    ExternalWrite,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ExecutionStatus {
    #[serde(rename = "RECEIVED")]
    Received,
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "WAITING")]
    Waiting,
    #[serde(rename = "VERIFYING")]
    Verifying,
    #[serde(rename = "PUBLISHING")]
    Publishing,
    #[serde(rename = "CANCELLING")]
    Cancelling,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "STOPPED")]
    Stopped,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum CompletionStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "SUCCEEDED")]
    Succeeded,
    #[serde(rename = "PARTIAL")]
    Partial,
    #[serde(rename = "OUTCOME_UNKNOWN")]
    OutcomeUnknown,
    #[serde(rename = "FAILED")]
    Failed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ActionState {
    #[serde(rename = "PROPOSED")]
    Proposed,
    #[serde(rename = "AUTHORIZED")]
    Authorized,
    #[serde(rename = "PREPARED")]
    Prepared,
    #[serde(rename = "DISPATCHING")]
    Dispatching,
    #[serde(rename = "ACKNOWLEDGED")]
    Acknowledged,
    #[serde(rename = "VERIFIED")]
    Verified,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "UNCERTAIN")]
    Uncertain,
    #[serde(rename = "COMPENSATED")]
    Compensated,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ReconciliationVerdict {
    #[serde(rename = "NOT_OBSERVED")]
    NotObserved,
    #[serde(rename = "CONFIRMED_APPLIED")]
    ConfirmedApplied,
    #[serde(rename = "CONFIRMED_NOT_APPLIED")]
    ConfirmedNotApplied,
    #[serde(rename = "APPLIED_MISMATCH")]
    AppliedMismatch,
    #[serde(rename = "UNCERTAIN")]
    Uncertain,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum SideEffectState {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "confirmed")]
    Confirmed,
    #[serde(rename = "uncertain")]
    Uncertain,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum VerificationResult {
    #[serde(rename = "pass")]
    Pass,
    #[serde(rename = "fail")]
    Fail,
    #[serde(rename = "inconclusive")]
    Inconclusive,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum PolicyDecision {
    #[serde(rename = "DENY")]
    Deny,
    #[serde(rename = "ALLOW")]
    Allow,
    #[serde(rename = "REQUIRE_DECISION")]
    RequireDecision,
    #[serde(rename = "HANDOFF")]
    Handoff,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InputSnapshot {
    pub ref: NonEmptyString,
    pub snapshot: SnapshotHash,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Deliverable {
    pub kind: NonEmptyString,
    pub name: NonEmptyString,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Budget {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_usd: Option<f64>,
    pub max_model_turns: PositiveCounter,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExternalEffectScope {
    pub capability: NonEmptyString,
    pub account_ref: NonEmptyString,
    pub target: NonEmptyString,
    pub purpose: NonEmptyString,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TaskContract {
    pub task_id: Identifier,
    pub contract_version: crate::SafeInteger,
    pub goal: NonEmptyString,
    pub inputs: Vec<InputSnapshot>,
    pub deliverables: Vec<Deliverable>,
    pub acceptance: Vec<Identifier>,
    pub external_effects: Vec<ExternalEffectScope>,
    pub budget: Budget,
    pub policy_profile_id: Identifier,
    pub on_budget_exhaustion: String,
    pub assumptions: Vec<NonEmptyString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<UtcTimestamp>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WaitCondition {
    pub reason: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_observation_at: Option<UtcTimestamp>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wake_event: Option<NonEmptyString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<UtcTimestamp>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TaskSnapshot {
    pub schema_version: crate::SafeInteger,
    pub task_id: Identifier,
    pub version: PositiveCounter,
    pub execution_status: ExecutionStatus,
    pub completion_status: CompletionStatus,
    pub cancel_epoch: Counter,
    pub unresolved_effects: Vec<Identifier>,
    pub unmet_required_criteria: Vec<Identifier>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait: Option<WaitCondition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result_manifest_ref: Option<ContentRef>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionRecord {
    pub schema_version: crate::SafeInteger,
    pub action_id: Identifier,
    pub task_id: Identifier,
    pub version: PositiveCounter,
    pub state: ActionState,
    pub effect: Effect,
    pub intent_hash: Sha256,
    pub payload_ref: ContentRef,
    pub method: NonEmptyString,
    pub endpoint: NonEmptyString,
    pub account_ref: NonEmptyString,
    pub target: NonEmptyString,
    pub policy_revision: PositiveCounter,
    pub cancel_epoch: Counter,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fencing_token: Option<PositiveCounter>,
    pub precondition_version: PositiveCounter,
    pub verifier_version: NonEmptyString,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<NonEmptyString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub idempotency_expires_at: Option<UtcTimestamp>,
    pub side_effect_state: SideEffectState,
    pub reconciliation_verdict: ReconciliationVerdict,
    pub acceptance_status: String,
    pub evidence_refs: Vec<NonEmptyString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipt_ref: Option<NonEmptyString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compensation_action_ref: Option<Identifier>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PermissionGrant {
    pub schema_version: crate::SafeInteger,
    pub grant_id: Identifier,
    pub task_id: Identifier,
    pub subject: Identifier,
    pub capability: NonEmptyString,
    pub resources: Vec<NonEmptyString>,
    pub effect: Effect,
    pub destinations: Vec<NonEmptyString>,
    pub purpose: NonEmptyString,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_limit_usd: Option<f64>,
    pub expires_at: UtcTimestamp,
    pub origin: String,
    pub policy_revision: PositiveCounter,
    pub cancel_epoch: Counter,
    pub fencing_token: PositiveCounter,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload_hash: Option<Sha256>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProviderCapabilityManifest {
    pub schema_version: crate::SafeInteger,
    pub adapter_id: Identifier,
    pub adapter_version: NonEmptyString,
    pub provider: Identifier,
    pub model: NonEmptyString,
    pub auth_kind: String,
    pub support_level: String,
    pub input_modalities: Vec<String>,
    pub structured_output: bool,
    pub tool_calls: bool,
    pub parallel_tool_calls: bool,
    pub reasoning_continuation: bool,
    pub context_limit: PositiveCounter,
    pub max_tool_result_bytes: PositiveCounter,
    pub usage_reporting: String,
    pub cancellation: String,
    pub native_computer_use: bool,
    pub output_budget_enforcement: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<UtcTimestamp>,
    pub evidence_refs: Vec<NonEmptyString>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Artifact {
    pub name: NonEmptyString,
    pub sha256: Sha256,
    pub mime: NonEmptyString,
    pub size_bytes: Counter,
    pub source_snapshot: SnapshotHash,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Verification {
    pub criterion_id: Identifier,
    pub method: NonEmptyString,
    pub tool_version: NonEmptyString,
    pub input_hash: SnapshotHash,
    pub result: VerificationResult,
    pub evidence_refs: Vec<NonEmptyString>,
    pub timestamp: UtcTimestamp,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactManifest {
    pub manifest_version: crate::SafeInteger,
    pub task_id: Identifier,
    pub result_version: PositiveCounter,
    pub status: String,
    pub artifacts: Vec<Artifact>,
    pub required_criteria: Vec<Identifier>,
    pub verification: Vec<Verification>,
    pub external_effect_receipts: Vec<NonEmptyString>,
    pub unresolved_effects: Vec<Identifier>,
    pub unmet_required_criteria: Vec<Identifier>,
    pub created_at: UtcTimestamp,
}

pub const CONTRACT_NAMES: &[&str] = &[
    "InputSnapshot",
    "Deliverable",
    "Budget",
    "ExternalEffectScope",
    "TaskContract",
    "WaitCondition",
    "TaskSnapshot",
    "ActionRecord",
    "PermissionGrant",
    "ProviderCapabilityManifest",
    "Artifact",
    "Verification",
    "ArtifactManifest",
];

impl crate::sealed::Sealed for InputSnapshot {}
impl crate::Contract for InputSnapshot { const NAME: &'static str = "InputSnapshot"; }
impl crate::sealed::Sealed for Deliverable {}
impl crate::Contract for Deliverable { const NAME: &'static str = "Deliverable"; }
impl crate::sealed::Sealed for Budget {}
impl crate::Contract for Budget { const NAME: &'static str = "Budget"; }
impl crate::sealed::Sealed for ExternalEffectScope {}
impl crate::Contract for ExternalEffectScope { const NAME: &'static str = "ExternalEffectScope"; }
impl crate::sealed::Sealed for TaskContract {}
impl crate::Contract for TaskContract { const NAME: &'static str = "TaskContract"; }
impl crate::sealed::Sealed for WaitCondition {}
impl crate::Contract for WaitCondition { const NAME: &'static str = "WaitCondition"; }
impl crate::sealed::Sealed for TaskSnapshot {}
impl crate::Contract for TaskSnapshot { const NAME: &'static str = "TaskSnapshot"; }
impl crate::sealed::Sealed for ActionRecord {}
impl crate::Contract for ActionRecord { const NAME: &'static str = "ActionRecord"; }
impl crate::sealed::Sealed for PermissionGrant {}
impl crate::Contract for PermissionGrant { const NAME: &'static str = "PermissionGrant"; }
impl crate::sealed::Sealed for ProviderCapabilityManifest {}
impl crate::Contract for ProviderCapabilityManifest { const NAME: &'static str = "ProviderCapabilityManifest"; }
impl crate::sealed::Sealed for Artifact {}
impl crate::Contract for Artifact { const NAME: &'static str = "Artifact"; }
impl crate::sealed::Sealed for Verification {}
impl crate::Contract for Verification { const NAME: &'static str = "Verification"; }
impl crate::sealed::Sealed for ArtifactManifest {}
impl crate::Contract for ArtifactManifest { const NAME: &'static str = "ArtifactManifest"; }

/// Graph membership only; not permission, replay safety, or dispatch admission.
pub fn is_action_transition_allowed(from: ActionState, to: ActionState) -> bool {
    match from {
        ActionState::Proposed => matches!(to, ActionState::Authorized | ActionState::Rejected),
        ActionState::Authorized => matches!(to, ActionState::Prepared | ActionState::Rejected),
        ActionState::Prepared => matches!(to, ActionState::Dispatching | ActionState::Rejected),
        ActionState::Dispatching => matches!(to, ActionState::Acknowledged | ActionState::Uncertain),
        ActionState::Acknowledged => matches!(to, ActionState::Verified | ActionState::Failed | ActionState::Uncertain | ActionState::Compensated),
        ActionState::Verified => matches!(to, ActionState::Compensated),
        ActionState::Rejected => false,
        ActionState::Failed => matches!(to, ActionState::Authorized),
        ActionState::Uncertain => matches!(to, ActionState::Acknowledged | ActionState::Verified | ActionState::Failed),
        ActionState::Compensated => false,
    }
}
