// Generated by scripts/generate-model-contracts.mjs. DO NOT EDIT.
// Stream completion is not tool authority or task completion.

pub type ModelId = String;

pub type ModelCounter = crate::SafeInteger;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelTextDelta {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelToolCallDelta {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub call_id: ModelId,
    pub chunk: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelToolCallComplete {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub call_id: ModelId,
    pub payload_json: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelReasoningHandle {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub encrypted_ref: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelUsage {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub input_tokens: ModelCounter,
    pub output_tokens: ModelCounter,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelRateLimit {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub retry_after_ms: crate::SafeInteger,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelCompleted {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub finish_reason: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelFailed {
    pub schema_version: crate::SafeInteger,
    pub request_id: ModelId,
    pub seq: crate::SafeInteger,
    pub r#type: String,
    pub category: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum ModelEvent {
    TextDelta(ModelTextDelta),
    ToolCallDelta(ModelToolCallDelta),
    ToolCallComplete(ModelToolCallComplete),
    ReasoningHandle(ModelReasoningHandle),
    Usage(ModelUsage),
    RateLimit(ModelRateLimit),
    Completed(ModelCompleted),
    Failed(ModelFailed),
}

pub const CONTRACT_NAMES: &[&str] = &[
    "ModelTextDelta",
    "ModelToolCallDelta",
    "ModelToolCallComplete",
    "ModelReasoningHandle",
    "ModelUsage",
    "ModelRateLimit",
    "ModelCompleted",
    "ModelFailed",
    "ModelEvent",
];

impl crate::sealed::Sealed for ModelTextDelta {}
impl crate::Contract for ModelTextDelta { const NAME: &'static str = "ModelTextDelta"; }
impl crate::sealed::Sealed for ModelToolCallDelta {}
impl crate::Contract for ModelToolCallDelta { const NAME: &'static str = "ModelToolCallDelta"; }
impl crate::sealed::Sealed for ModelToolCallComplete {}
impl crate::Contract for ModelToolCallComplete { const NAME: &'static str = "ModelToolCallComplete"; }
impl crate::sealed::Sealed for ModelReasoningHandle {}
impl crate::Contract for ModelReasoningHandle { const NAME: &'static str = "ModelReasoningHandle"; }
impl crate::sealed::Sealed for ModelUsage {}
impl crate::Contract for ModelUsage { const NAME: &'static str = "ModelUsage"; }
impl crate::sealed::Sealed for ModelRateLimit {}
impl crate::Contract for ModelRateLimit { const NAME: &'static str = "ModelRateLimit"; }
impl crate::sealed::Sealed for ModelCompleted {}
impl crate::Contract for ModelCompleted { const NAME: &'static str = "ModelCompleted"; }
impl crate::sealed::Sealed for ModelFailed {}
impl crate::Contract for ModelFailed { const NAME: &'static str = "ModelFailed"; }
impl crate::sealed::Sealed for ModelEvent {}
impl crate::Contract for ModelEvent { const NAME: &'static str = "ModelEvent"; }
