// Generated by scripts/generate-worker-contracts.mjs. DO NOT EDIT.
// Value validation is not channel authentication or current authority.

pub type WorkerId = String;

pub type WorkerText = String;

pub type WorkerHash = String;

pub type WorkerCounter = crate::SafeInteger;

pub type WorkerPositive = crate::SafeInteger;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum WorkerDecision {
    #[serde(rename = "DENY")]
    Deny,
    #[serde(rename = "ALLOW")]
    Allow,
    #[serde(rename = "REQUIRE_DECISION")]
    RequireDecision,
    #[serde(rename = "HANDOFF")]
    Handoff,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum WorkerOrigin {
    #[serde(rename = "user_request")]
    UserRequest,
    #[serde(rename = "user_decision")]
    UserDecision,
    #[serde(rename = "local_policy")]
    LocalPolicy,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerRule {
    pub tool: WorkerId,
    pub tool_version: WorkerPositive,
    pub resource: WorkerText,
    pub purpose: WorkerText,
    pub decision: WorkerDecision,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerPolicy {
    pub schema_version: crate::SafeInteger,
    pub profile_id: WorkerId,
    pub revision: WorkerPositive,
    pub origin: WorkerOrigin,
    pub denied_tools: Vec<WorkerId>,
    pub rules: Vec<WorkerRule>,
    pub max_calls: crate::SafeInteger,
    pub grant_ttl_ms: crate::SafeInteger,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerArguments {
    pub expected_hash: WorkerHash,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerProposal {
    pub schema_version: crate::SafeInteger,
    pub call_id: WorkerId,
    pub task_id: WorkerId,
    pub tool: WorkerId,
    pub tool_version: WorkerPositive,
    pub resource: WorkerText,
    pub purpose: WorkerText,
    pub arguments: WorkerArguments,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerGrant {
    pub schema_version: crate::SafeInteger,
    pub grant_id: WorkerId,
    pub subject: WorkerId,
    pub task_id: WorkerId,
    pub tool: WorkerId,
    pub tool_version: WorkerPositive,
    pub resource: WorkerText,
    pub purpose: WorkerText,
    pub payload_hash: WorkerHash,
    pub profile_id: WorkerId,
    pub policy_revision: WorkerPositive,
    pub generation: WorkerPositive,
    pub cancel_epoch: WorkerCounter,
    pub fencing_token: WorkerPositive,
    pub expires_at_ms: WorkerPositive,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerAuthorization {
    pub schema_version: crate::SafeInteger,
    pub decision: WorkerDecision,
    pub reason: WorkerId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub grant: Option<WorkerGrant>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerCall {
    pub grant_ref: WorkerId,
    pub proposal: WorkerProposal,
    pub policy_revision: WorkerPositive,
    pub generation: WorkerPositive,
    pub cancel_epoch: WorkerCounter,
    pub fencing_token: WorkerPositive,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerRequest {
    pub jsonrpc: String,
    pub id: WorkerId,
    pub method: String,
    pub params: WorkerCall,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerResult {
    pub schema_version: crate::SafeInteger,
    pub call_id: WorkerId,
    pub grant_ref: WorkerId,
    pub status: String,
    pub side_effect_state: String,
    pub contract_hash: WorkerHash,
    pub evidence_ref: WorkerId,
    pub replayed: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerReply {
    pub jsonrpc: String,
    pub id: WorkerId,
    pub result: WorkerResult,
}

pub const CONTRACT_NAMES: &[&str] = &[
    "WorkerRule",
    "WorkerPolicy",
    "WorkerArguments",
    "WorkerProposal",
    "WorkerGrant",
    "WorkerAuthorization",
    "WorkerCall",
    "WorkerRequest",
    "WorkerResult",
    "WorkerReply",
];

impl crate::sealed::Sealed for WorkerRule {}
impl crate::Contract for WorkerRule { const NAME: &'static str = "WorkerRule"; }
impl crate::sealed::Sealed for WorkerPolicy {}
impl crate::Contract for WorkerPolicy { const NAME: &'static str = "WorkerPolicy"; }
impl crate::sealed::Sealed for WorkerArguments {}
impl crate::Contract for WorkerArguments { const NAME: &'static str = "WorkerArguments"; }
impl crate::sealed::Sealed for WorkerProposal {}
impl crate::Contract for WorkerProposal { const NAME: &'static str = "WorkerProposal"; }
impl crate::sealed::Sealed for WorkerGrant {}
impl crate::Contract for WorkerGrant { const NAME: &'static str = "WorkerGrant"; }
impl crate::sealed::Sealed for WorkerAuthorization {}
impl crate::Contract for WorkerAuthorization { const NAME: &'static str = "WorkerAuthorization"; }
impl crate::sealed::Sealed for WorkerCall {}
impl crate::Contract for WorkerCall { const NAME: &'static str = "WorkerCall"; }
impl crate::sealed::Sealed for WorkerRequest {}
impl crate::Contract for WorkerRequest { const NAME: &'static str = "WorkerRequest"; }
impl crate::sealed::Sealed for WorkerResult {}
impl crate::Contract for WorkerResult { const NAME: &'static str = "WorkerResult"; }
impl crate::sealed::Sealed for WorkerReply {}
impl crate::Contract for WorkerReply { const NAME: &'static str = "WorkerReply"; }
