[package]
name = "tada-local-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tada-store = { path = "../store" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
getrandom = "=0.3.4"
tokio = { version = "=1.53.1", default-features = false, features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "process"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "=0.2.189"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Pipes", "Win32_System_Threading", "Win32_System_Memory"] }
